// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD5txjxaqIr5X4TaZv2pPN5fLVYKbj1D9o',
    appId: '1:1038764892657:web:7fbc616f8a5edeb1dfe450',
    messagingSenderId: '1038764892657',
    projectId: 'bookswap-app-f1922',
    authDomain: 'bookswap-app-f1922.firebaseapp.com',
    storageBucket: 'bookswap-app-f1922.firebasestorage.app',
    measurementId: 'G-PF488PM5K5',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAa2FRQZ2vWqkE0b4rR1uD5sci5fo27IhE',
    appId: '1:1038764892657:android:9e5acec0f1bb0761dfe450',
    messagingSenderId: '1038764892657',
    projectId: 'bookswap-app-f1922',
    storageBucket: 'bookswap-app-f1922.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCP1uCF28meKXLSTpLnoOGg7TT2WPf4Obw',
    appId: '1:1038764892657:ios:51d1614cc82e003cdfe450',
    messagingSenderId: '1038764892657',
    projectId: 'bookswap-app-f1922',
    storageBucket: 'bookswap-app-f1922.firebasestorage.app',
    iosBundleId: 'com.example.individualAssignment2',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCP1uCF28meKXLSTpLnoOGg7TT2WPf4Obw',
    appId: '1:1038764892657:ios:51d1614cc82e003cdfe450',
    messagingSenderId: '1038764892657',
    projectId: 'bookswap-app-f1922',
    storageBucket: 'bookswap-app-f1922.firebasestorage.app',
    iosBundleId: 'com.example.individualAssignment2',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD5txjxaqIr5X4TaZv2pPN5fLVYKbj1D9o',
    appId: '1:1038764892657:web:656d677ff39dccbfdfe450',
    messagingSenderId: '1038764892657',
    projectId: 'bookswap-app-f1922',
    authDomain: 'bookswap-app-f1922.firebaseapp.com',
    storageBucket: 'bookswap-app-f1922.firebasestorage.app',
    measurementId: 'G-62G8FXRKQ1',
  );

}